BYTES_ONE_CHARS = 4
PAGES = 100
LINES = 50
CHARS = 25
VOLUME = 1.44
TOTAL_CHARS = PAGES * LINES * CHARS
BOOK_VOLUME = BYTES_ONE_CHARS * TOTAL_CHARS
DISK_SIZE = VOLUME * 1024 * 1024
NUM_BOOKS = DISK_SIZE//BOOK_VOLUME

print(f'КОЛИЧЕСТВО КНИГ:', NUM_BOOKS)